### ISSUE TITLE
When I try to create a comment with empty content

### ISSUE THREAD

**Issue by efrapp** [Redvanisation/insta-social#6]
Please validate this case:
<img width="331" alt="Screen Shot 2019-10-29 at 5 06 46 PM" src="https://user-images.githubusercontent.com/698811/67813045-9387ae00-fa6e-11e9-8055-721e5eee85df.png">

**Comment by Redvanisation** [comment]
This happened because there was no redirect to after you enter an invalid comment, issue solved.
